"""定义仓库读取和补丁写入工具必须满足的接口。"""

from pathlib import Path
from typing import Protocol


class RepositoryToolsProtocol(Protocol):
    def list_files(self, workspace: Path) -> list[str]: ...

    def read_file(self, workspace: Path, relative_path: str) -> str: ...

    def search_text(self, workspace: Path, query: str) -> list[str]: ...

    def git_diff(self, workspace: Path) -> str: ...


class EditToolsProtocol(Protocol):
    def apply_patch(self, workspace: Path, patch: str) -> None: ...


class GitToolsProtocol(Protocol):
    def base_commit(self, workspace: Path) -> str: ...

    def changed_files(self, workspace: Path) -> list[str]: ...

    def diff(self, workspace: Path) -> str: ...

    def create_patch(self, workspace: Path) -> str: ...
